export const DEFAULT_SETTINGS = {
  appearanceMode: "automatic",
  appIconMode: "automatic",
  language: "english",
  notificationsEnabled: true,
  reminderNotificationsEnabled: true,
  marketingNotificationsEnabled: false,
  soundsEnabled: true,
  completionSoundId: "success_default",
  failureSoundId: "failure_default",
  notificationSoundId: "notification_default",
  weekStartsOn: "monday",
  sortCompletedMode: "moveDown",
  sortSkippedMode: "moveDown",
  appBadgeEnabled: false,
  includeDailyInBadge: true,
  includeWeeklyInBadge: true,
  includeMonthlyInBadge: true,
  quietHoursEnabled: false,
  quietHoursStart: null,
  quietHoursEnd: null,
  widgetActionMode: "openHabit",
  distanceUnit: "km",
  volumeUnit: "ml",
  startOfDay: "12:00 am",
  vacationModeEnabled: false,
  vacationModeScope: "allHabits",
  vacationModeHabitIds: [],
} as const;
